# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customerPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowCustomer(object):
    def setupUi(self, MainWindowCustomer):
        MainWindowCustomer.setObjectName("MainWindowCustomer")
        MainWindowCustomer.resize(977, 480)
# omit this part of the code



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowCustomer = QtWidgets.QMainWindow()
    ui = Ui_MainWindowCustomer()
    ui.setupUi(MainWindowCustomer)
    MainWindowCustomer.show()
    sys.exit(app.exec_())
