# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rentVehiclePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowRentVehicle(object):
    def setupUi(self, MainWindowRentVehicle):
        MainWindowRentVehicle.setObjectName("MainWindowRentVehicle")
        MainWindowRentVehicle.resize(977, 480)
        
        # omit this part of the code

        
