# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'topUpBalancePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowTopUpBalance(object):
    def setupUi(self, MainWindowTopUpBalance):
        MainWindowTopUpBalance.setObjectName("MainWindowTopUpBalance")
        MainWindowTopUpBalance.resize(977, 480)
# omit this part of the code